[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["fmt", "--all"]

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["clippy", "--all-features", "--", "-D", "warnings"]

[build]
target = "index.html"
dist = "dist"
release = true

[watch]
ignore = ["dist"]

[serve]
port = 8080
address = "127.0.0.1"
